name: Build and Deploy Sphinx Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/gh-pages.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Install the latest version of uv
        id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
            version: "latest"
            enable-cache: true
            cache-suffix: "docbuild"

      - name: Print uv debug information
        run: |
          echo "Installed uv version is ${{ steps.setup-uv.outputs.uv-version }}"
          echo "Installed uv path is ${{ steps.setup-uv.outputs.uv-path }}"
          echo "Set Python version is ${{ steps.setup-uv.outputs.python-version }}"

      - name: Install dependencies
        run: uv sync --frozen --group docs

      - name: Build documentation
        run: |
          uv run make -C docs html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
    
      - name: Print documentation URL
        run: |
            echo "Your documentation will be available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"