---
name: Ruff
on: [ pull_request ]

permissions:
  contents: read
  pull-requests: write # Required for posting comments

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # Check for formatting errors (but don't fix them)

      - uses: astral-sh/ruff-action@v3
        with:
          github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          args: "check"
